# Generated by Django 4.2 on 2023-05-02 04:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinateModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created date')),
                ('modified', models.DateTimeField(blank=True, editable=False, verbose_name='modified date')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.0'), max_digits=30, verbose_name='longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, default=Decimal('0.0'), max_digits=30, verbose_name='latitude')),
            ],
            options={
                'verbose_name': 'Test Coordinate Model',
                'verbose_name_plural': 'Test Coordinate Models',
            },
        ),
    ]
