name: pytest

on:
  pull_request:
  push:
    branches:
      - master, develop

env:
  DJANGO_SETTINGS_MODULE: testapp.settings

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        tox-django-version: ['32', '40, '41']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox

      - name: Test with pytest
        run: tox -e py-dj${{ matrix.tox-django-version }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}